CREATE TABLE BBS
(	
	no VARCHAR2(100),
	TITLE VARCHAR2(100),
	CONTENT VARCHAR2(100),
	WRITER VARCHAR2(100)
)

CREATE TABLE MEMBER(	
	ID VARCHAR2(10),
	PW VARCHAR2(10),
	NAME VARCHAR2(10),
	TEL VARCHAR2(10)
  )
  
  CREATE TABLE PRODUCT(
ID VARCHAR2(200),
NAME VARCHAR2(200),
CONTENT VARCHAR2(200),
PRICE VARCHAR2(200),
COMPANY VARCHAR2(200),
IMG VARCHAR2(200)
)


CREATE TABLE orderlist (
	"no" VARCHAR2(100),
	member_id VARCHAR2(100),
	product_id VARCHAR2(100),
	total_id VARCHAR2(100)
)

CREATE TABLE depart (
	id VARCHAR2(100),
	name VARCHAR2(100),
	instructor VARCHAR2(100)
)

CREATE TABLE student (
	id VARCHAR2(100),
	name VARCHAR2(100),
	tel VARCHAR2(100),
	depart_id VARCHAR2(100)
)

CREATE TABLE subject (
	id VARCHAR2(100),
	title VARCHAR2(100),
	depart_id VARCHAR2(100)
)

CREATE TABLE "HR"."BBS2" 
(	"no" VARCHAR2(100), 
	"TITLE" VARCHAR2(100), 
	"CONTENT" VARCHAR2(100), 
	"WRITER" VARCHAR2(100), 
	 CONSTRAINT "BBS_PK22" PRIMARY KEY ("no"),
	 CONSTRAINT "FK_MEMBER22" FOREIGN KEY ("WRITER")
	  REFERENCES "HR"."MEMBER" ("ID")
) 

CREATE TABLE "HR"."BBS3" (
	"no" VARCHAR2(100), 
	"TITLE" VARCHAR2(100), 
	"CONTENT" VARCHAR2(100), 
	"WRITER" VARCHAR2(100)
) 

--pk제약조건 추가
ALTER TABLE HR.BBS3
ADD CONSTRAINT BBS3_PK
PRIMARY KEY ("no")

--kf제약조건 추가
ALTER TABLE HR.BBS3 
ADD CONSTRAINT FK_MEMBER33 
FOREIGN KEY (WRITER) REFERENCES HR."MEMBER"(ID);

CREATE TABLE "HR"."depart2" (
	"id" VARCHAR2(100), 
	"name" VARCHAR2(100), 
	"instructor" VARCHAR2(100) 
)

ALTER TABLE HR."depart2"
ADD CONSTRAINT DEPART2_PK 
PRIMARY KEY ("id")

CREATE TABLE "HR"."student2" (
	"id" VARCHAR2(100), 
	"name" VARCHAR2(100), 
	"tel" VARCHAR2(100),
	"depart_id" VARCHAR2(100)
)

ALTER TABLE HR."student2"
ADD CONSTRAINT STUDENT2_PK 
PRIMARY KEY ("id")

ALTER TABLE HR."student2"
ADD CONSTRAINT "FK_depart2" 
FOREIGN KEY ("depart_id") 
REFERENCES HR."depart2"("id");


CREATE TABLE member22
AS SELECT *FROM MEMBER

INSERT INTO member22 
VALUES ('banana3', 'banana3', 'banana3', 'banana3', sysdate)

SELECT * FROM MEMBER22 

INSERT INTO member22 
VALUES ('banana4', 'banana4', 'banana4', 'banana4', sysdate, 'aaa')

INSERT INTO bbs3
VALUES (bbs_id_seq.nextval, 'happy', 'happy day', 'ice')

INSERT INTO bbs3
VALUES (bbs_id_seq.nextval, 'happy2', 'happy day2', 'ice')

SELECT *FROM bbs3

CREATE SEQUENCE pd_id_seq 
INCREMENT BY 1 
START WITH 1

CREATE TABLE product3 (
	id number(38,0),
	name varchar2(100)
)

INSERT INTO PRODUCT3 
VALUES (pd_id_seq.nextval, 'shoes')

SELECT * FROM product3

CREATE SEQUENCE or_seq 
INCREMENT BY 1 
START WITH 1

CREATE TABLE orderlist3(
	id number(38,0),
	title varchar2(100),
	price number(38,0)
)

INSERT INTO orderlist3
VALUES (or_seq.nextval,'sorry', 275)

SELECT * FROM orderlist3
WHERE id >=3
ORDER BY id DESC  

CREATE TABLE DEPT
(
DEPTNO NUMBER(2),
DNAME VARCHAR2(14 BYTE),
LOC VARCHAR2(13 BYTE)
)

CREATE TABLE EMP
(
EMPNO NUMBER(4),
ENAME VARCHAR2(10 BYTE),
JOB VARCHAR2(9 BYTE),
MGR NUMBER(4),
HIREDATE DATE,
SAL NUMBER(7,2),
COMM NUMBER(7,2),
DEPTNO NUMBER(2)
)

CREATE TABLE SALGRADE
(
GRADE NUMBER,
LOSAL NUMBER,
HISAL NUMBER
)

ALTER TABLE DEPT ADD (
CONSTRAINT PK_DEPT
PRIMARY KEY
(DEPTNO));

ALTER TABLE EMP ADD (
CONSTRAINT PK_EMP
PRIMARY KEY
(EMPNO));

ALTER TABLE EMP ADD (
CONSTRAINT FK_DEPTNO
FOREIGN KEY (DEPTNO)
REFERENCES DEPT (DEPTNO));

SELECT * FROM emp --selection

SELECT deptno FROM emp

SELECT DISTINCT deptno FROM emp

SELECT ename, sal * 12 FROM emp

SELECT * FROM emp 
ORDER BY sal DESC 

SELECT * FROM emp 
WHERE NOT deptno = 30
ORDER BY empno DESC 

SELECT * FROM emp 
WHERE deptno = 30 AND job  = 'SALESMAN'

SELECT * FROM emp 
WHERE deptno = 30 or job  = 'SALESMAN'

SELECT * FROM emp 
WHERE sal >= 3000

SELECT * FROM emp 
WHERE sal != 3000

SELECT * FROM emp 
WHERE job NOT IN ('SALESMAN', 'MANAGER')
ORDER BY JOB 

SELECT * FROM emp 
WHERE sal BETWEEN 2000 AND 3000
ORDER BY empno 

SELECT * FROM emp 
WHERE ENAME LIKE '_L%'

SELECT * FROM emp 
WHERE ENAME NOT LIKE '_L%'

SELECT * FROM emp 
WHERE COMM IS NULL 

SELECT * FROM emp 
WHERE COMM IS NOT NULL 

CREATE TABLE DEPT_TEMP2
AS 
SELECT * FROM DEPT

SELECT * FROM DEPT_TEMP2

UPDATE DEPT_TEMP2
SET LOC ='SEOUL'

UPDATE DEPT_TEMP2
SET DNAME ='DATABASE', loc = 'BUSAN'

DELETE FROM DEPT_TEMP2
WHERE DNAME ='SALES'

SELECT * FROM DEPT_TEMP2

CREATE TABLE PRODUCT3
(	"ID" VARCHAR2(200),
"NAME" VARCHAR2(200),
"CONTENT" VARCHAR2(200),
"PRICE" NUMBER(38,0),
"COMPANY" VARCHAR2(200),
"IMG" VARCHAR2(200)
)
--2
SELECT * FROM PRODUCT3
ORDER BY PRICE DESC

--3
SELECT 'NAME', 'CONTENT', PRICE FROM PRODUCT3
ORDER BY COMPANY

--4
SELECT DISTINCT COMPANY FROM PRODUCT3

--5
SELECT PRICE * 5 AS PRICE5 FROM PRODUCT3

--6
SELECT COMPANY , NAME FROM PRODUCT3 WHERE PRICE = '5000'

--7
SELECT NAME, PRICE, COMPANY FROM PRODUCT3 
WHERE PRICE BETWEEN 3000 AND 6000

--8
SELECT COMPANY, NAME FROM PRODUCT3
WHERE COMPANY != 'c100'

--9
SELECT NAME, PRICE FROM PRODUCT3 
WHERE COMPANY = 'c100' OR company = 'c200'

--10
SELECT * FROM PRODUCT3 
WHERE NAME LIKE '%4'

--11
SELECT * FROM PRODUCT3 
WHERE CONTENT LIKE '%food%'

--12
UPDATE PRODUCT3 
SET CONTENT = '품절' WHERE PRICE = 5000

--13
UPDATE PRODUCT3 
SET PRICE = 10000 , IMG = 'O.PNG' WHERE id = 100 AND id =102 

--14
DELETE FROM PRODUCT3
WHERE COMPANY = 'c100'

--15
DELETE FROM PRODUCT3

SELECT * FROM PRODUCT3
